### ISSUE TITLE
Assert error, even with no pages provided

### ISSUE THREAD

**Issue by jasonkaruza** [aagarwal1012/IntroViews-Flutter#35]
**Describe the bug**
Assert error.
```
main.<fn>
FlutterError.reportError
RenderObject._debugReportException
RenderObject.layout
_RenderInputPadding.performLayout
RenderObject.layout
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
RenderObject.layout
RenderPadding.performLayout
RenderObject.layou
I/flutter ( 4847): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4847): The following assertion was thrown during performLayout():
I/flutter ( 4847): BoxConstraints forces an infinite width.
I/flutter ( 4847): These invalid constraints were provided to RenderCustomPaint's layout() function by the following
I/flutter ( 4847): function, which probably computed the invalid constraints in question:
I/flutter ( 4847):   RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 4847): The offending constraints were:
I/flutter ( 4847):   BoxConstraints(w=Infinity, 36.0<=h<=Infinity)
I/flutter ( 4847):
I/flutter ( 4847): When the exception was thrown, this was the stack:
I/flutter ( 4847): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError 
I/flutter ( 4847): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> 
I/flutter ( 4847): #2      BoxConstraints.debugAssertIsValid 
I/flutter ( 4847): #3      RenderObject.layout 
I/flutter ( 4847): #4      RenderConstrainedBox.performLayout 
I/flutter ( 4847): #5      RenderObject.layout 
I/flutter ( 4847): #6      _RenderInputPadding.performLayout 
I/flutter ( 4847): #7      RenderObject.layout 
I/flutter ( 4847): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #9      RenderObject.layout 
I/flutter ( 4847): #10     RenderPadding.performLayout 
I/flutter ( 4847): #11     RenderObject.layout 
I/flutter ( 4847): #12     RenderFlex.performLayout 
I/flutter ( 4847): #13     RenderObject.layout 
I/flutter ( 4847): #14     RenderStack.performLayout 
I/flutter ( 4847): #15     RenderObject.layout 
I/flutter ( 4847): #16     MultiChildLayoutDelegate.layoutChild 
I/flutter ( 4847): #17     _ScaffoldLayout.performLayout 
I/flutter ( 4847): #18     MultiChildLayoutDelegate._callPerformLayout 
I/flutter ( 4847): #19     RenderCustomMultiChildLayoutBox.performLayout 
I/flutter ( 4847): #20     RenderObject.layout 
I/flutter ( 4847): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #22     RenderObject.layout 
I/flutter ( 4847): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #24     _RenderCustomClip.performLayout 
I/flutter ( 4847): #25     RenderObject.layout 
I/flutter ( 4847): #26     MultiChildLayoutDelegate.layoutChild 
I/flutter ( 4847): #27     _ScaffoldLayout.performLayout 
I/flutter ( 4847): #28     MultiChildLayoutDelegate._callPerformLayout 
I/flutter ( 4847): #29     RenderCustomMultiChildLayoutBox.performLayout 
I/flutter ( 4847): #30     RenderObject.layout 
I/flutter ( 4847): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #32     RenderObject.layout 
I/flutter ( 4847): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #34     _RenderCustomClip.performLayout 
I/flutter ( 4847): #35     RenderObject.layout 
I/flutter ( 4847): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #37     RenderObject.layout 
I/flutter ( 4847): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #39     RenderObject.layout 
I/flutter ( 4847): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #41     RenderObject.layout 
I/flutter ( 4847): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #43     RenderObject.layout 
I/flutter ( 4847): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #45     RenderObject.layout 
I/flutter ( 4847): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #47     RenderObject.layout 
I/flutter ( 4847): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #49     RenderObject.layout 
I/flutter ( 4847): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #51     RenderOffstage.performLayout 
I/flutter ( 4847): #52     RenderObject.layout 
I/flutter ( 4847): #53     RenderStack.performLayout 
I/flutter ( 4847): #54     RenderObject.layout 
I/flutter ( 4847): #55     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #56     RenderObject.layout 
I/flutter ( 4847): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #58     RenderObject.layout 
I/flutter ( 4847): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #60     RenderObject.layout 
I/flutter ( 4847): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #62     RenderObject.layout 
I/flutter ( 4847): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #64     RenderObject.layout 
I/flutter ( 4847): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter ( 4847): #66     RenderObject.layout 
I/flutter ( 4847): #67     RenderView.performLayout 
I/flutter ( 4847): #68     RenderObject._layoutWithoutResize 
I/flutter ( 4847): #69     PipelineOwner.flushLayout 
I/flutter ( 4847): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
I/flutter ( 4847): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
I/flutter ( 4847): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
I/flutter ( 4847): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
I/flutter ( 4847): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
I/flutter ( 4847): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
I/flutter ( 4847): #77     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 4847): #78     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 4847): #79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter ( 4847): (elided one frame from package dart:async-patch)
I/flutter ( 4847):
I/flutter ( 4847): The following RenderObject was being processed when the exception was fired:
I/flutter ( 4847):   RenderConstrainedBox#1020b relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4847):   creator: ConstrainedBox ← _InputPadding ← Semantics ← RawMaterialButton ← FlatButton ← DoneButton
I/flutter ( 4847):   ← Padding ← Row ← DefaultTextStyle ← Positioned ← PageIndicatorButtons ← Stack ← ⋯
I/flutter ( 4847):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter ( 4847):   constraints: BoxConstraints(unconstrained)
I/flutter ( 4847):   size: MISSING
I/flutter ( 4847):   additionalConstraints: BoxConstraints(w=Infinity, 36.0<=h<=Infinity)
I/flutter ( 4847): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 4847):   RenderCustomPaint#f1a00 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4847):     _RenderInkFeatures#f4690 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4847):       RenderSemanticsGestureHandler#613ff NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4847):         RenderPointerListener#c8766 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4847):           RenderPadding#fde30 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4847): 
```

**To Reproduce**
```
Flutter doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.3)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```
Steps to reproduce the behavior (this sample code):
```
 @override
  Widget build(BuildContext context) {
    Log.logFunctionName("_Onboarding", "build()");
    // Store when we have a context
    stateData.setBuildContext(context);

    // TODO: Remove when done testing
    _initPages();

    return WillPopScope(
        onWillPop: () async => false,
        child: Scaffold(
          appBar: AppBar(
            backgroundColor: Colors.transparent,
            centerTitle: true,
            elevation: 0.0,
            title: textTitle,
          ),
          body: Builder(
            builder: (context) => IntroViewsFlutter(
                  [],
                  onTapSkipButton: _finish,
                  onTapDoneButton: _finish,
                  pageButtonTextStyles: TextStyle(
                    color: Colors.white,
                    fontSize: 18.0,
                  ),
                  showSkipButton: true,
                ),
        )));
  }
```

**Expected behavior**
No errors. It still renders, but the exceptions are not a good sign.

**Smartphone (please complete the following information):**
 - Pixel 2 Emulator on Android Pie

**Comment by jasonkaruza** [comment]
The issue appears to be with the build() method of PageIndicatorButtons class. Specifically the below code:

```
Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            Padding(
                padding: const EdgeInsets.only(bottom: 10.0),
                child: _getSkipORBackButton() //Row
                ), //Padding
            Padding(
                padding: const EdgeInsets.only(bottom: 10.0),
                child: _getDoneORNextButton() //Row
                )
          ],
        ),
```
Something about trying to render the buttons within a row is causing exceptions.
